// Copyright (C) 2014 Diego Herranz

#include <pic18fregs.h>
#include <delay.h>

// FUSES START
// Minimum modifications needed. Rest of fuses left as default.

//The code generated by SDCC does probably not work when XINST (extended instruction set) is enabled
#pragma config XINST=OFF

// Single-Supply ICSP ON
#pragma config LVP = ON

// If this is ON, MCLR must be connected to VDD
#pragma config MCLRE = OFF

// FUSES END

#define LED_LAT LATCbits.LATC0
#define LED_TRIS TRISCbits.TRISC0

void main(void)
{
	LED_TRIS = 0; // Pin as output
	LED_LAT = 0; // LED off
	
	while (1) {
		LED_LAT = !LED_LAT; // Toggle LED
		delay1ktcy(50);
	}
}
